##编写项目的配置文件
server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: vio_tuku
  datasource:
    url: jdbc:mysql://localhost:3306/vio_tuku
    username: root
    password: '@087174Ab'
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #逻辑删除
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.vio.aitukuviobe.controller

## 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: xxx
#    secretId: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx

## 阿里云 AI 配置
#aliYunAi:
#  apiKey: xxx