package com.vio.aitukuviobe.infrastructure.api.aliyunai.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 创建扩图任务请求（调用阿里云百炼 API 使用）
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateOutPaintingTaskRequest {

    /**
     * 模型
     */
    private String model = "image-out-painting";

    /**
     * 输入信息
     */
    private Input input;

    /**
     * 图像处理参数
     */
    private Parameters parameters;

    @Data
    public static class Input {
        /**
         * 图片 URL
         */
        private String imageUrl;
    }

    @Data
    public static class Parameters {
        /**
         * 可选，图像居中，在水平方向上按比例扩展，默认值 1.0，范围 [1.0, 3.0]
         * 注意：@JsonProperty 将 Java 的 xScale 映射为 API 要求的 x_scale (snake_case)
         */
        @JsonProperty("x_scale")
        private Float xScale;

        /**
         * 可选，图像居中，在垂直方向上按比例扩展，默认值 1.0，范围 [1.0, 3.0]
         */
        @JsonProperty("y_scale")
        private Float yScale;

        /**
         * 可选，添加 "Generated by AI" 水印，默认值 false
         */
        @JsonProperty("add_watermark")
        private Boolean addWatermark = false;
    }
}
